# Name of the action (will show in the UI when you see a list of all your runs)
name: GitHub Actions Demo

# What action to trigger (we want this action to run whenever there's an event called push)
on: [push]

# Job that get triggered when "push" event happens (if multiple jobs specified, they run in parallel
jobs:
  # Name of the job 
  my-first-job:
    # Operating system (in this case latest verion of ubuntu)
    runs-on: ubuntu-latest
    steps:

      # Third party action (workflow) from Github to clone contents of the current repo
      #   - structure: organisation/repo_name@version
      - uses: actions/checkout@v3
    
      # We can give a name to each step
      # ${{ }} used for special variables about context of the run: 
      #   - check https://docs.github.com/en/actions/learn-github-actions/contexts)
      - name: hello
        run: echo "hello world"
      
      # If we want our run to be in multiple lines, follow the syntax below
      - name: run python script
        run: |
          pip install -r requirements.txt
          python ci.py
        
